# Generated by Django 2.2.5 on 2020-01-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_nbr', models.PositiveIntegerField()),
                ('balance', models.IntegerField()),
                ('acct_type', models.CharField(max_length=2)),
            ],
        ),
    ]
