# Generated by Django 2.2.5 on 2020-01-16 17:39

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=80, unique=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cnp_nbr', encrypted_model_fields.fields.EncryptedCharField(default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
